# This creates a (manually triggered) Quarks Job to rotate all generated
# secrets.
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksJob
metadata:
  name: secret-rotation
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- list $ "secret-rotation" | include "component.labels" | nindent 4 }}
spec:
  trigger:
    strategy: manual
  template:
    spec:
      template:
        spec:
          containers:
          - name: generate-rotation-config-map
            {{- with $image := index $.Values.releases "secret-rotation" "image" }}
            image: {{ printf "%s:%s" $image.repository $image.tag }}
            imagePullPolicy: {{ $image.pullPolicy | quote }}
            {{- end }}
            command:
            - /usr/bin/env
            - ruby
            - -e
            - |
              {{- .Files.Get "assets/scripts/helm/secret-rotation/rotate-secrets.rb" | nindent 14 }}
            env:
            - name: DEPLOYMENT
              value: {{ include "kubecf.deployment-name" . | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          restartPolicy: Never
          serviceAccountName: secret-rotation
        automountServiceAccountToken: true
---
# We require a ServiceAccount with access to listing QuarksSecrets
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-rotation
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- list $ "secret-rotation" | include "component.labels" | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-rotation
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- list $ "secret-rotation" | include "component.labels" | nindent 4 }}
rules:
- apiGroups: [ quarks.cloudfoundry.org ]
  resources: [ quarkssecrets ]
  verbs: [ list ]
- apiGroups: [ '' ]
  resources: [ configmaps ]
  verbs: [ create ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-rotation
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- list $ "secret-rotation" | include "component.labels" | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote}}
  name: secret-rotation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-rotation
