dependencies:
- name: eirini
  version: 1.0.5
  repository: http://opensource.suse.com/eirini-release/
  condition: features.eirini.enabled
- name: bits
  version: 1.0.17
  repository: http://opensource.suse.com/bits-service-release/
  condition: features.eirini.enabled
- name: eirini-extensions
  alias: eirinix
  repository: https://opensource.suse.com/eirinix-helm-release/
  version: "v0.0.0-11+gf340692"
  condition: features.eirini.enabled
