{{- if .Values.features.eirini.enabled -}}

# A service for the cc uploader
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cc-uploader
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  selector:
    quarks.cloudfoundry.org/instance-group-name: api
    quarks.cloudfoundry.org/deployment-name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      name: "http"
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: "https"
      port: 9091
      targetPort: 9091
# A service for the eirini image registry
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-eirini-registry
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: NodePort
  selector:
    quarks.cloudfoundry.org/instance-group-name: bits
    quarks.cloudfoundry.org/deployment-name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: {{ .Values.features.eirini.registry.service.nodePort }}
---
# A namespace where eirini apps are created
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}-eirini
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-eirini
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini:all
  namespace: {{ .Release.Name }}-eirini
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs:     ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini:all
  namespace: {{ .Release.Name }}-eirini
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eirini:all
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-eirini
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ops-remove-diego
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/component: operations
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "kubecf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "kubecf.chart" . }}
data:
  ops: |
    # Remove the whole diego-cell instance group.
    - type: remove
      path: /instance_groups/name=diego-cell

    # Remove bbs and silk-controller from diego-api.
    # TODO: remove bbs in the future - when the clock and worker no longer need it.
    # - type: remove
    #   path: /instance_groups/name=diego-api/jobs/name=bbs

    # Remove auctioneer, tps and ssh_proxy from scheduler.
    - type: remove
      path: /instance_groups/name=scheduler/jobs/name=auctioneer
    - type: remove
      path: /instance_groups/name=scheduler/jobs/name=tps
    - type: remove
      path: /instance_groups/name=scheduler/jobs/name=ssh_proxy

{{- end }}
