{{- if .Values.releases.credentials -}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registry-credentials
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/name: {{ include "scf.fullname" . }}
    app.kubernetes.io/version: {{ default .Chart.Version .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "scf.chart" . }}
data:
  .dockerconfigjson: {{ printf "{%q:{%q:{%q:%q,%q:%q,%q:%q}}}" "auths" .Values.releases.credentials.hostname "username" .Values.releases.credentials.username "password" .Values.releases.credentials.password "auth" (printf "%s:%s" .Values.releases.credentials.username .Values.releases.credentials.password | b64enc) | b64enc }}
{{- end }}
