
# Add quarks properties for log-cache.
- type: replace
  path: /instance_groups/name=log-cache/jobs/name=log-cache/properties/health_addr?
  value: "::6060"
- type: replace
  path: /instance_groups/name=log-cache/jobs/name=log-cache/properties/quarks?
  value:
    ports:
    - name: log-cache
      protocol: TCP
      internal: 8080
    run:
      healthcheck:
        log-cache:
          readiness:
            exec:
              command:
              - curl
              - --insecure
              - --fail
              - --head
              - --silent
              - --cert
              - /var/vcap/jobs/log-cache/config/certs/metrics.crt
              - --key
              - /var/vcap/jobs/log-cache/config/certs/metrics.key
              - https://localhost:6060/debug/pprof/cmdline

- type: replace
  path: /instance_groups/name=log-cache/jobs/name=log-cache-gateway/properties/quarks?/run/healthcheck/log-cache-gateway
  value:
    readiness:
      # Unfortunately, by default the health port listens on localhost only
      # and isn't easily configurable
      exec:
        command:
        - curl
        - --insecure
        - --fail
        - --head
        - --silent
        - --cert
        - /var/vcap/jobs/log-cache/config/certs/metrics.crt
        - --key
        - /var/vcap/jobs/log-cache/config/certs/metrics.key
        - https://localhost:6063/debug/pprof/cmdline

- type: replace
  path: /instance_groups/name=log-cache/jobs/name=log-cache-nozzle/properties/quarks?/run/healthcheck/log-cache-nozzle
  value:
    readiness:
      # Unfortunately, by default the health port listens on localhost only
      # and isn't easily configurable
      exec:
        command: [curl, --fail, --head, --silent, http://localhost:6061/debug/pprof/cmdline]

- type: replace
  path: /instance_groups/name=log-cache/jobs/name=log-cache-cf-auth-proxy/properties/quarks?/run/healthcheck/log-cache-cf-auth-proxy
  value:
    readiness:
      # Unfortunately, by default the health port listens on localhost only
      # and isn't easily configurable
      exec:
        command:
        - curl
        - --insecure
        - --fail
        - --head
        - --silent
        - --cert
        - /var/vcap/jobs/log-cache/config/certs/metrics.crt
        - --key
        - /var/vcap/jobs/log-cache/config/certs/metrics.key
        - https://localhost:6065/debug/pprof/cmdline
